// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Robot.
#pragma once

#include <frc/I2C.h>
#include <frc/Timer.h>
#include <frc/TimedRobot.h>
#include <frc2/command/Command.h>

#include "RobotContainer.h"

class Robot : public frc::TimedRobot {
 public:
  Robot();
  void RobotInit() override;
  void RobotPeriodic() override;
  void DisabledInit() override;
  void DisabledPeriodic() override;
  void AutonomousInit() override;
  void AutonomousPeriodic() override;
  void TeleopInit() override;
  void TeleopPeriodic() override;
  void TestPeriodic() override;

 private:
  // Have it null by default so that if testing teleop it
  // doesn't have undefined behavior and potentially crash.
  frc2::Command* m_autonomousCommand = nullptr;

  RobotContainer* m_container = RobotContainer::GetInstance();
  frc::I2C m_imu{frc::I2C::Port::kOnboard, 0x68};
  uint8_t m_matchState{0};
  frc::Timer m_cmdVelWatchdog;
  frc::Timer m_matchTimer;         // starts at AutonomousInit(); measures elapsed match time
  bool m_matchStarted{false};      // true once autonomous or teleop begins
  bool m_roboClawOk{false};
  bool m_seenArmedCommand{false};
  double m_matchTimeRemaining{180.0};  // seconds; diagnostic only
  void ReadIMU();
};
