// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

#pragma once

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

#include <frc/Timer.h>
#include <frc2/command/CommandHelper.h>
#include <frc2/command/Command.h>
#include <units/time.h>


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class Drivetrain;

/**
 *
 *
 * @author ExampleAuthor
 */
class AutonomousCommand: public frc2::CommandHelper<frc2::Command, AutonomousCommand> {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    explicit AutonomousCommand(Drivetrain& drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

void Initialize() override;
void Execute() override;
bool IsFinished() override;
void End(bool interrupted) override;
bool RunsWhenDisabled() const override;


private:
    enum class Phase { DEPART, SWEEP_FORWARD, SWEEP_TURN, STOP };
    Drivetrain& m_drivetrain;
    Phase m_phase{Phase::DEPART};
    frc::Timer m_phaseTimer;
    int m_sweepLane{0};
    static constexpr int kTotalSweepLanes = 4;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES




    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};
