// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/AutonomousCommand.h"

#include "subsystems/Drivetrain.h"

AutonomousCommand::AutonomousCommand(Drivetrain& drivetrain)
    : m_drivetrain(drivetrain) {

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("AutonomousCommand");
    AddRequirements(&m_drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
  m_phase = Phase::DEPART;
  m_phaseTimer.Reset();
  m_phaseTimer.Start();
  m_drivetrain.ResetOdometry(0.15, 0.15, 0.0);
  m_sweepLane = 0;
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
  auto& dt = m_drivetrain;

  switch (m_phase) {
    case Phase::DEPART:
      dt.Drive(0.3, 0.0, 0.0);
      if (m_phaseTimer.Get() > 2.0_s) {
        m_phase = Phase::SWEEP_FORWARD;
        m_phaseTimer.Reset();
      }
      break;
    case Phase::SWEEP_FORWARD:
      dt.Drive(0.3, 0.0, 0.0);
      if (m_phaseTimer.Get() > 3.0_s) {  // drive ~0.9m per lane
        m_phase = Phase::SWEEP_TURN;
        m_phaseTimer.Reset();
      }
      break;
    case Phase::SWEEP_TURN:
      dt.Drive(0.0, (m_sweepLane % 2 == 0) ? 0.3 : -0.3, 0.0);  // shift one lane
      if (m_phaseTimer.Get() > 0.7_s) {                         // ~0.2m lateral shift
        m_sweepLane++;
        m_phase = (m_sweepLane < kTotalSweepLanes) ? Phase::SWEEP_FORWARD
                                                   : Phase::STOP;
        m_phaseTimer.Reset();
      }
      break;
    case Phase::STOP:
      dt.StopDrive();
      break;
  }
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
  return m_phase == Phase::STOP || false;
}

// Called once after isFinished returns true
void AutonomousCommand::End(bool interrupted) {
  m_drivetrain.StopDrive();
}

bool AutonomousCommand::RunsWhenDisabled() const {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
